# Generated by Django 3.0.5 on 2020-04-16 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EcoadsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain_area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('website', models.CharField(max_length=600)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EcoadsSitesParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoadsSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.EcoadsSite')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='ecoadssite',
            name='parameters',
            field=models.ManyToManyField(through='ecos.EcoadsSitesParameters', to='ecos.Parameter'),
        ),
    ]
