# Generated by Django 2.2.12 on 2020-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directive',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='parameter_name',
        ),
        migrations.AddField(
            model_name='parameter',
            name='definition_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='preferred_label_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='uri',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
