# Generated by Django 2.2.12 on 2020-04-21 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0002_auto_20200421_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain_area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('website', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='EcosSitesDataSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.DataSource')),
                ('ecos_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.EcosSite')),
            ],
        ),
        migrations.RemoveField(
            model_name='ecoadssitesparameters',
            name='ecoadsSite',
        ),
        migrations.RemoveField(
            model_name='ecoadssitesparameters',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='EcoadsSite',
        ),
        migrations.DeleteModel(
            name='EcoadsSitesParameters',
        ),
        migrations.AddField(
            model_name='ecossite',
            name='data_source',
            field=models.ManyToManyField(through='ecos.EcosSitesDataSources', to='ecos.DataSource'),
        ),
    ]
