# Generated by Django 2.2.12 on 2020-04-22 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0003_auto_20200421_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='datasource',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='datasource',
            name='observation_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sampling_frequency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='sampling_start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='temporal_coverage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='temporal_resolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='update_frequency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='ParametersDataSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.DataSource')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.Parameter')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='data_source',
            field=models.ManyToManyField(through='ecos.ParametersDataSources', to='ecos.DataSource'),
        ),
    ]
