# Generated by Django 2.2.12 on 2020-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0004_auto_20200422_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='sampling_start_date',
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='website',
            field=models.URLField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='uri',
            field=models.URLField(max_length=600, null=True),
        ),
    ]
