# Generated by Django 2.2.12 on 2020-04-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0005_auto_20200423_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='domain_area',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='location',
        ),
    ]
