# Generated by Django 2.2.12 on 2020-04-23 11:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0006_auto_20200423_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='datasource',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
