# Generated by Django 2.2.12 on 2020-05-08 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0008_auto_20200428_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecossite',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
