# Generated by Django 2.2.12 on 2020-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0009_auto_20200508_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='suffix',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
