# Generated by Django 2.2.12 on 2020-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0010_ecossite_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
