# Generated by Django 2.2.12 on 2020-05-26 14:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0011_ecossite_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
