# Generated by Django 2.2.12 on 2020-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0012_auto_20200526_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='ecoss',
            field=models.BooleanField(default=False),
        ),
    ]
