# Generated by Django 2.2.13 on 2020-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0014_auto_20200605_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametersDataSources',
            new_name='DataSourcesParameters',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='data_source',
        ),
        migrations.AddField(
            model_name='datasource',
            name='parameters',
            field=models.ManyToManyField(through='ecos.DataSourcesParameters', to='ecos.Parameter'),
        ),
    ]
