# Generated by Django 2.2.13 on 2020-06-29 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0015_auto_20200619_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
