# Generated by Django 2.2.13 on 2020-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0017_auto_20200803_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='is_fixoss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecossite',
            name='is_lter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecossite',
            name='is_n2k',
            field=models.BooleanField(default=False),
        ),
    ]
