# Generated by Django 2.2.13 on 2020-11-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0020_measure_serie'),
        ('ecos', '0020_ecossite_conceptualmodel'),
    ]

    operations = [
    ]
