# Generated by Django 2.2.13 on 2020-11-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0011_auto_20201118_1256'),
        ('ecos', '0021_merge_20201117_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecossite',
            name='conceptualmodel',
        ),
        migrations.CreateModel(
            name='EcosSitesCMPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptualmodels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos_cm.CMPage')),
                ('ecos_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecos.EcosSite')),
            ],
        ),
        migrations.AddField(
            model_name='ecossite',
            name='conceptualmodels',
            field=models.ManyToManyField(through='ecos.EcosSitesCMPages', to='ecos_cm.CMPage'),
        ),
    ]
