# Generated by Django 2.2.13 on 2021-03-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0022_auto_20201118_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='parameter',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
