# Generated by Django 2.2.13 on 2021-03-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0023_auto_20210312_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcesparameters',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='datasourcesparameters',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='ecossitesdatasources',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='ecossitesdatasources',
            name='ecos_site',
        ),
        migrations.RemoveField(
            model_name='ecossite',
            name='data_source',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='DataSourcesParameters',
        ),
        migrations.DeleteModel(
            name='EcosSitesDataSources',
        ),
    ]
