# Generated by Django 3.1.7 on 2021-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0025_auto_20210318_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecossite',
            name='is_onmap',
            field=models.BooleanField(default=False),
        ),
    ]
