# Generated by Django 3.1.7 on 2021-04-27 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0026_ecossite_is_onmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecossite',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
