# Generated by Django 3.1.7 on 2021-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0027_auto_20210427_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecossite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='img',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='website',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
