# Generated by Django 3.1.7 on 2021-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0017_station_description'),
        ('ecos_cm', '0011_auto_20201118_1256'),
        ('ecos', '0028_auto_20210427_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecossite',
            name='conceptualmodels',
            field=models.ManyToManyField(blank=True, through='ecos.EcosSitesCMPages', to='ecos_cm.CMPage'),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='measurement_location_id',
            field=models.ManyToManyField(blank=True, through='ecos.EcosSitesLocationDjangoMeasurements', to='measurements.Location'),
        ),
        migrations.AlterField(
            model_name='ecossite',
            name='parameters',
            field=models.ManyToManyField(blank=True, through='ecos.EcosSitesParameters', to='ecos.Parameter'),
        ),
    ]
