# Generated by Django 3.1.7 on 2021-05-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0032_auto_20210504_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcosSitesInfoResource',
            new_name='EcosSitesInfoResources',
        ),
    ]
