# Generated by Django 3.1.7 on 2021-05-13 16:24

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0034_inforesource_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforesource',
            name='data_access_information',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inforesource',
            name='info_resource_type',
            field=models.CharField(choices=[('Monitoring program', 'Monitoring program'), ('Portal', 'Portal'), ('Geospatial layer', 'Geospatial layer'), ('Dataset', 'Dataset'), ('Other', 'Other')], default='Monitoring program', max_length=100),
        ),
    ]
