# Generated by Django 3.1.7 on 2021-06-06 09:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0038_auto_20210521_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforesource',
            name='info_resource_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monitoring program', 'Monitoring program'), ('Portal', 'Portal'), ('Map', 'Map'), ('Dataset', 'Dataset'), ('Data Source', 'Data Source'), ('Other', 'Other')], max_length=55),
        ),
    ]
