# Generated by Django 3.1.7 on 2021-06-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0039_auto_20210606_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforesource',
            name='embed_url',
            field=models.URLField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
