# Generated by Django 3.1.7 on 2021-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0040_inforesource_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforesource',
            name='embed_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
