# Generated by Django 2.2.13 on 2020-06-15 09:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200417_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='null'),
            preserve_default=False,
        ),
    ]
