# Generated by Django 2.2.13 on 2020-06-15 09:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200615_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='null'),
            preserve_default=False,
        ),
    ]
