# Generated by Django 2.2.12 on 2020-04-17 07:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='flexpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
