# Generated by Django 2.2.12 on 2020-04-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20200417_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='flexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
