# Generated by Django 2.2.12 on 2020-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20200417_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_subtitle',
        ),
    ]
