# Generated by Django 2.2.13 on 2020-12-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0007_auto_20201029_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='banner_image',
        ),
    ]
