# Generated by Django 2.2.13 on 2020-11-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('ecos_cm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpage',
            old_name='subtitle',
            new_name='model_title',
        ),
        migrations.AddField(
            model_name='cmpage',
            name='model_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
