# Generated by Django 2.2.13 on 2020-11-10 15:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0002_auto_20201110_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpage',
            name='model_hi',
            field=wagtail.core.fields.RichTextField(default='text'),
            preserve_default=False,
        ),
    ]
