# Generated by Django 2.2.13 on 2020-11-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0006_auto_20201110_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_ep',
            new_name='cm_ecolagical_processes',
        ),
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_human_interactions',
            new_name='cm_human_interactions',
        ),
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_image',
            new_name='cm_image',
        ),
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_ov',
            new_name='cm_oceanographic_variables',
        ),
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_pi',
            new_name='cm_performance_indicators',
        ),
        migrations.RenameField(
            model_name='cmpage',
            old_name='model_title',
            new_name='cm_title',
        ),
    ]
