# Generated by Django 2.2.13 on 2020-11-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecos', '0019_ecossite_img'),
        ('ecos_cm', '0007_auto_20201110_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpage',
            name='ecossite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecos.EcosSite'),
        ),
    ]
