# Generated by Django 2.2.13 on 2020-11-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0008_cmpage_ecossite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpage',
            name='ecossite',
        ),
    ]
