# Generated by Django 2.2.13 on 2020-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0009_remove_cmpage_ecossite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpage',
            name='conceptual_model',
            field=models.CharField(choices=[('ecological processes', 'ecological processes'), ('target species', 'target species')], default='ecological processes', max_length=100),
        ),
    ]
