# Generated by Django 2.2.13 on 2020-11-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_cm', '0010_cmpage_conceptual_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpage',
            old_name='conceptual_model',
            new_name='conceptual_model_type',
        ),
    ]
